# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 04:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170311_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 4, 18, 1, 157309)),
        ),
    ]
