# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170311_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avtar',
            field=models.ImageField(default='/avatar/no-img.jpg', null=True, upload_to='/avatar'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='no-img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 9, 54, 10, 362152)),
        ),
    ]
