# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170311_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 10, 4, 48, 289225)),
        ),
    ]
