# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170320_0143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepComment',
            new_name='ReplayComment',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 1, 44, 34, 204243)),
        ),
    ]
