# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170320_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replaycomment',
            old_name='replay',
            new_name='reply',
        ),
        migrations.AddField(
            model_name='replaycomment',
            name='fullname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 6, 35, 58, 656005)),
        ),
    ]
