# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170320_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 30, 8, 56, 0, 464208)),
        ),
    ]
